apiVersion: batch/v1
kind: Job
metadata:
  name: openshift-service-catalog-apiserver-remover
  namespace: openshift-service-catalog-removed
spec:
  template:
    spec:
      serviceAccountName: openshift-service-catalog-apiserver-remover
      containers:
      - name: openshift-service-catalog-apiserver-remover
        # image will be some registry image
        image: registry.svc.ci.openshift.org/openshift/origin-v4.0:cluster-svcat-apiserver-operator
        command: ["/usr/bin/cluster-svcat-apiserver-remover"]
        resources:
          requests:
            memory: 50Mi
      restartPolicy: Never
  backoffLimit: 4
