apiVersion: v1
kind: Namespace
metadata:
  labels:
  name: openshift-service-catalog-apiserver-operator
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true"
