apiVersion: operator.openshift.io/v1
kind: ServiceCatalogAPIServer
metadata:
  name: cluster
  annotations:
    release.openshift.io/create-only: "true"
spec:
  logLevel: Normal
  managementState: Removed
